import { LockOutlined, SchoolOutlined } from '@mui/icons-material';
import { Box, Button, Card, CardContent, TextField, Typography } from '@mui/material';
import { useState, type FormEvent } from 'react';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/useAuth';
import type { AuthUser } from '../../context/auth-context';

const demoUser: AuthUser = { id:'ADMIN-001', firstName:'System', lastName:'Administrator', email:'admin@university.ac.ke', role:'Administrator' };
export default function LoginPage(){const {isAuthenticated,signIn}=useAuth();const navigate=useNavigate();const location=useLocation();const [email,setEmail]=useState('admin@university.ac.ke');const [password,setPassword]=useState('');if(isAuthenticated)return <Navigate to="/dashboard" replace/>;const submit=(e:FormEvent)=>{e.preventDefault();signIn({...demoUser,email:email||demoUser.email},'demo-access-token');navigate((location.state as {from?:string}|null)?.from??'/dashboard',{replace:true});};return <Box sx={{minHeight:'100vh',display:'grid',placeItems:'center',bgcolor:'background.default',p:2}}><Card sx={{width:'100%',maxWidth:440}}><CardContent sx={{p:4}}><Box sx={{display:'flex',alignItems:'center',gap:1.5,mb:3}}><Box sx={{width:48,height:48,borderRadius:2,bgcolor:'primary.main',color:'primary.contrastText',display:'grid',placeItems:'center'}}><SchoolOutlined/></Box><Box><Typography variant="h5" sx={{fontWeight:700}}>University Management System</Typography><Typography variant="body2" color="text.secondary">Administration Portal</Typography></Box></Box><Typography variant="h6" sx={{fontWeight:700}}>Sign in</Typography><Typography variant="body2" color="text.secondary" sx={{mt:.5,mb:3}}>Use the administrator account to continue.</Typography><Box component="form" onSubmit={submit} sx={{display:'grid',gap:2}}><TextField label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><TextField label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required helperText="Demo authentication is active until the backend API is connected."/><Button type="submit" variant="contained" size="large" startIcon={<LockOutlined/>}>Sign in</Button></Box></CardContent></Card></Box>}
